server:
  port: 8888
  servlet:
      session:
        tracking-modes: cookie
        cookie:
          http-only: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/black?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  rabbitmq:
      host: 10.50.10.49
      port: 5672
      username: guest
      password: XjJr1btllOmW
      virtual-host: /
cas:
  server:
    urlPrefix: https://sso-test.digi800.com/cas
    loginUrl: https://sso-test.digi800.com/cas/login
    logoutUrl: https://sso-test.digi800.com/cas/logout
  client:
    url: http://localhost:8888/
    login: http://localhost:8888/login
    logout: http://localhost:8888/logout
    index: http://localhost:8888/index
  # 动态开启 cas 单点登录
  loginType: cas
  # cas 验票拦截路径
  urlPattern: /*
  # cas不拦截的路径
  ignorePattern: /static/*|/api/*|/test/*
  # cas的路径
  urls: '{"test":"https://sso-test.digi800.com",
          "AZ":"https://sso.gaoyaya.com"
         }'

