server:
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: lebbay-hr  #用于指定注册到EurekaServer 上的应用名称
  profiles:
      active: @profiles.active@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.50.10.48:3306/hr_test3?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: richardsun
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
      request-context-attribute: rc
      settings:
        classic_compatible: true
      #设置响应的内容类型
      content-type: text/html;charset=utf-8
      suffix: .ftl
      #是否允许mvc使用freemarker
      enabled: true
      #是否开启template caching
      cache: false
      #设定模板的加载路径，多个以逗号分隔，默认: [“classpath:/templates/”]
      template-loader-path: classpath:/templates/
      #设定Template的编码
      charset: UTF-8
  resources:
      static-locations: [classpath:/static]
  mvc:
      static-path-pattern: /static/**
#整合Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
  mapper-locations: classpath*:/mapper/**/*.xml #加载mapper.xml文件
  type-aliases-package: com.lebbay.hr.**.model #别名扫描


##